[tool.poetry]
name = "cicd-test"
version = "0.1.0"
description = ""
authors = ["Magistra Apta <31767116+magistraapta@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
