name: CI for FastAPI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  docker:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to DockerHub (if needed)
    # Uncomment and configure if you want to push images to DockerHub
    # - name: Log in to DockerHub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build Docker image
    - name: Build Docker Image
      run: |
        docker build -t fastapi-app .

    # Step 4: Test Docker Container
    - name: Test Docker Container
      run: |
        docker run --rm -d -p 8000:8000 fastapi-app
        sleep 5  # Wait for the container to start
        curl -f http://localhost:8000

    # Step 5: Push to DockerHub (optional)
    # Uncomment if you want to push the built image to DockerHub
    # - name: Push Docker Image
    #   run: |
    #     docker tag fastapi-app username/fastapi-app:latest
    #     docker push username/fastapi-app:latest
